config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'posts#index'
  resources :tweets do
    resources :comments, only: :create
  end
  resources :users, only: [:show, :edit, :update]
  get 'posts/music', to: 'posts#music'
  get 'posts/about', to: 'posts#about'
  get 'posts/video', to: 'posts#video'
  get 'posts/tour', to: 'posts#tour'
  get 'posts/news', to: 'posts#news'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :music
end

app/models/music.rb
class Music < ApplicationRecord

  belongs_to :user
  has_many :favorites
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  validates :text, presence: true
  belongs_to :user
  has_many :comments

  def self.search(search)
    return Tweet.all unless search
    Tweet.where('text LIKE(?)', "%#{search}%")
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :musics
  has_many :favorites
  has_many :favorite_musics, through: :favorites, source: :music
  has_many :tweets
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.create(comment_params)
    respond_to do |format|
      format.html {redirect_to "/tweets/#{@comment.tweet.id}"}
      format.json
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, tweet_id: params[:tweet_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
  end

  def music
  end

  def about
  end

  def video
  end

  def tour
  end

  def news
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  def index
    @tweets = Tweet.includes(:user).order("created_at DESC").page(params[:page]).per(4)
  end

  def new
    @tweet = Tweet.new
  end

  def create
    Tweet.create(tweet_params)
    redirect_to tweets_path
  end

  def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy
  end

  def edit
    @tweet = Tweet.find(params[:id])
  end

  def update
    tweet = Tweet.find(params[:id])
    tweet.update(tweet_params)
  end

  def show
    @tweet = Tweet.find(params[:id])
    @comment = Comment.new
    @comments = @tweet.comments.includes(:user)
  end

  def search
    @tweets = Tweet.search(params[:keyword])
  end

  private
  def tweet_params
    params.require(:tweet).permit(:image, :text).merge(user_id: current_user.id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    user = User.find(params[:id])
    @name = current_user.name
    @tweets = user.tweets.order("created_at DESC").page(params[:page]).per(4)
  end

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_notifications.html.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title OneokrockChat
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %link{:href => "//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css", :rel => "stylesheet", :type => "text/css"}/
    %link{:href => "//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css", :rel => "stylesheet", :type => "text/css"}/
    %script{:src => "//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js", :type => "text/javascript"}/
    %script{src: "assets/js/tour.js", type: "text/javascript"}

  %body
    = render 'layouts/notifications'
    = yield

app/views/posts/about.html.haml
%header
  .header_base
    %h1
      = link_to image_tag("http://www.oneokrock.com/wp-content/themes/oor_pc/images/common/logo_top.png"), "/"
  .main_base
    .two_col
      .main_col
        #about
          %h2
            %img{:alt => "ABOUT", :src => "http://www.oneokrock.com/wp-content/themes/oor_pc/images/common/h2_about.png"}/
          .portrait
            %img{:alt => "portrait", :src => "http://www.oneokrock.com/wp-content/uploads/2018/11/OOR181123about.jpg"}/
          %h3.name
            %img{:alt => "ONE OK ROCK", :src => "http://www.oneokrock.com/wp-content/themes/oor_pc/images/about/h3_oneokrock.png"}/
          .intro
            %p.p1
              %span.s1> 2005年にバンド結成。エモ、ロックを軸にしたサウンドとアグレッシブなライブパフォーマンスが若い世代に支持されてきた。
            %p.p1
              %span.s1> 2007年にデビューして以来、全国ライブハウスツアーや各地夏フェスを中心に積極的にライブを行う。これまでに、武道館、野外スタジアム公演、大規模な全国アリーナツアーなどを成功させる。
              %span.s1> 2016年には
              %span.s1> 11万人規模を動員する野外ライブを、
              %span.s1> 2018年は東京ドーム
              %span.s1> 2日間を含む全国ドームツアを開催。
            %p.p1
              日本のみならず海外レーベルとの契約をし、アルバム発売を経てアメリカ、ヨーロッパ、アジアでのワールドツアーを 成功させるなど世界基準のバンドになってきている。
              %span.s1> 2019年
              %span.s1> 2月にはニューアルバム「
              %span.s1>Eye of the Storm」を全世界で同時リリースが決定
          %ul.member_list
            %li
              %img{:alt => "VOCALS : TAKA , BORN ON  1988.4.17 / TOKYO", :src => "http://www.oneokrock.com/wp-content/themes/oor_pc/images/about/taka.png"}/
            %li
              %img{:alt => "GUITARS : TORU , BORN ON  1988.12.7 / OSAKA", :src => "http://www.oneokrock.com/wp-content/themes/oor_pc/images/about/toru.png"}/
            %li
              %img{:alt => "BASS : RYOTA , BORN ON  1989.9.4 / OSAKA", :src => "http://www.oneokrock.com/wp-content/themes/oor_pc/images/about/ryota.png"}/
            %li
              %img{:alt => "DRUMS : TOMOYA , BORN ON  1987.6.27 / HYOGO", :src => "http://www.oneokrock.com/wp-content/themes/oor_pc/images/about/tomoya.png"}/
      .sub_col
        #sns
          %ul.sns_list
            %li
              %a.o{:href => "https://twitter.com/ONEOKROCK_japan", :target => "_blank"}
                %i.icon_twitter
                  %img{:src => "http://www.oneokrock.com/wp-content/themes/oor_pc/images/sprite/twitter.png"}/
            %li
              %a.o{:href => "https://www.facebook.com/ONEOKROCK", :target => "_blank"}
                %i.icon_facebook
                  %img{:src => "http://www.oneokrock.com/wp-content/themes/oor_pc/images/sprite/facebook.png"}/
            %li
              %a.o{:href => "http://instagram.com/oneokrockofficial", :target => "_blank"}
                %i.icon_instagram
                  %img{:src => "http://www.oneokrock.com/wp-content/themes/oor_pc/images/sprite/instagram.png"}/
            %li
              %a.o{:href => "https://www.youtube.com/user/ONEOKROCKchannel", :target => "_blank"}
                %i.icon_youtube
                  %img{:src => "http://www.oneokrock.com/wp-content/themes/oor_pc/images/sprite/youtube.png"}/
            %li
              %a.o{:href => "http://smarturl.it/ONEOKROCK", :target => "_blank"}
                %i.icon_itune
                  %img{:src => "http://www.oneokrock.com/wp-content/themes/oor_pc/images/sprite/itune.png"}/
            %li
              %a.o{:href => "https://play.spotify.com/artist/7k73EtZwoPs516ZxE72KsO", :target => "_blank"}
                %i.icon_spotify
                  %img{:src => "http://www.oneokrock.com/wp-content/themes/oor_pc/images/sprite/spotify.png"}/
        -# sns
        #pickup_video
          .youtube
            %iframe{:allowfullscreen => "", :frameborder => "0", :height => "208", :src => "http://www.youtube.com/embed/uyaKoj7wABY/?wmode=transparent", :width => "369"}
          %p.more
            %a.o.inverse{:href => ""}
              %img{:alt => "MORE VIDEOS", :src => "http://www.oneokrock.com/wp-content/themes/oor_pc/images/common/btn_more_videos.png"}/
        -# pickup_video
        #twitter_widget
          %h2
            %img{:alt => "TWITTER", :src => "http://www.oneokrock.com/wp-content/themes/oor_pc/images/common/h2_twitter.png"}/
          %p.follow
            %a.o{:href => "http://twitter.com/ONEOKROCK_japan", :target => "_blank"}
              %img{:alt => "FOLLOW", :src => "http://www.oneokrock.com/wp-content/themes/oor_pc/images/common/btn_follow.png"}/
        -# twitter_widget
        #side_banners
          %ul.banner_list
            %li
              %a.o{:href => "https://oneokrock-pf.com/", :target => "_blank"}
                %img{:alt => "", :src => "http://www.oneokrock.com/wp-content/themes/oor_pc/images/side_banner/side_banner_1.png"}/
            %li
              %a.o{:href => "https://oneokrock-pf.com/", :target => "_blank"}
                %img{:alt => "", :src => "http://www.oneokrock.com/wp-content/themes/oor_pc/images/side_banner/side_banner_2.png"}/
          %iframe#twitter-widget-0.twitter-timeline.twitter-timeline-rendered{:allowfullscreen => "true", :allowtransparency => "true", "data-widget-id" => "profile:ONEOKROCK_japan", :frameborder => "0", :scrolling => "no", :style => "position: static; visibility: visible; display: inline-block; width: 100%; height: 360px; padding: 0px; border: none; max-width: 100%; min-width: 180px; margin-top: 0px; margin-bottom: 0px; min-height: 200px; z-index:20;", :title => "Twitterタイムライン"}
    #return_top
      %a.o{:href => "#"}
        %img{:alt => "RETURN PAGE TOP", :src => "http://www.oneokrock.com/wp-content/themes/oor_pc/images/common/btn_return_top.png"}/
  %footer
    .content_base
      %p.copyright
        %img{:alt => "copyright", :height => "8", :src => "http://www.oneokrock.com/wp-content/themes/oor_pc/images/common/copyright.png", :width => "179"}/

app/views/posts/index.html.haml
%header
  .header_base
    %h1
      %img{:alt => "ONE OK ROCK", :src => "http://www.oneokrock.com/wp-content/themes/oor_pc/images/common/logo_top.png"}
    %nav#glo_nav
      %ul
        %li.home_current
          %a.home_btn{:href => ""}
            %img.hf.on{:alt => "HOME", :src => "http://www.oneokrock.com/wp-content/themes/oor_pc/images/common/glo_home_on.png", :style => "position: absolute; opacity: 0; left: 43px; top: 0px; z-index: 0;"}/
            %img.hf{:alt => "HOME", :src => "http://www.oneokrock.com/wp-content/themes/oor_pc/images/common/glo_home_off.png"}/
        %li.news
          %a.news_btn
          =link_to "posts/news" do
            %img.hf.on{:alt => "NEWS", :src => "http://www.oneokrock.com/wp-content/themes/oor_pc/images/common/glo_news_on.png", :style => "position: absolute; opacity: 0; left: 180px; top: 0px; z-index: 0;"}/
            %img.hf{:alt => "NEWS", :src => "http://www.oneokrock.com/wp-content/themes/oor_pc/images/common/glo_news_off.png"}/
        %li.tour
          %a.tour_btn
          =link_to "posts/tour" do
            %img.hf.on{:alt => "TOUR", :src => "http://www.oneokrock.com/wp-content/themes/oor_pc/images/common/glo_tour_on.png", :style => "position: absolute; opacity: 0; left: 0px; top: 0px; z-index: 0;"}/
            %img.hf{:alt => "TOUR", :src => "http://www.oneokrock.com/wp-content/themes/oor_pc/images/common/glo_tour_off.png", :style => "opacity: 1;"}/
        %li.about
          %a.about_btn
          =link_to "posts/about" do
            %img.hf.on{:alt => "ABOUT", :src => "http://www.oneokrock.com/wp-content/themes/oor_pc/images/common/glo_about_on.png", :style => "position: absolute; opacity: 0; left: 0px; top: 0px; z-index: 0;"}/
            %img.hf{:alt => "ABOUT", :src => "http://www.oneokrock.com/wp-content/themes/oor_pc/images/common/glo_about_off.png", :style => "opacity: 1;"}/
        %li.videos
          %a.videos_btn
          =link_to "posts/video" do
            %img.hf.on{:alt => "VIDEOS", :src => "http://www.oneokrock.com/wp-content/themes/oor_pc/images/common/glo_videos_on.png", :style => "position: absolute; opacity: 0; left: 0px; top: 0px; z-index: 0;"}/
            %img.hf{:alt => "VIDEOS", :src => "http://www.oneokrock.com/wp-content/themes/oor_pc/images/common/glo_videos_off.png", :style => "opacity: 1;"}/
        %li.music
          %a.music_btn
          =link_to "posts/music" do
            %img.hf.on{:alt => "MUSIC", :src => "http://www.oneokrock.com/wp-content/themes/oor_pc/images/common/glo_music_on.png", :style => "position: absolute; opacity: 0; left: 0px; top: 0px; z-index: 0;"}/
            %img.hf{:alt => "MUSIC", :src => "http://www.oneokrock.com/wp-content/themes/oor_pc/images/common/glo_music_off.png", :style => "opacity: 1;"}/
        %li.store
          %a.store_btn{:href => ""}
            %img.hf.on{:alt => "STORE", :src => "http://www.oneokrock.com/wp-content/themes/oor_pc/images/common/glo_store_on.png", :style => "position: absolute; opacity: 0; left: 0px; top: 0px; z-index: 0;"}/
            %img.hf{:alt => "STORE", :src => "http://www.oneokrock.com/wp-content/themes/oor_pc/images/common/glo_store_off.png"}/
    .lang
      %a.lang_btn
        =link_to edit_user_path(current_user)do
          Log in
        %img.hf{:src => "http://www.oneokrock.com/wp-content/themes/oor_pc/images/sprite/caret-right.png"}/
      .content_btn
        =link_to tweets_path(current_user) do
          List of posts
        %img.hf{:src => "http://www.oneokrock.com/wp-content/themes/oor_pc/images/sprite/caret-right.png"}/
      .content_btn
        =link_to "/users/#{current_user.id}" do
          My page
        %img.hf{:src => "http://www.oneokrock.com/wp-content/themes/oor_pc/images/sprite/caret-right.png"}/

        -# %i.icon_caret-right
  -# .header_base
  
  .main_base
    #main_banner
      .control
        %a.prev{:href => ""}
          %img.h{:alt => "", :src => "http://www.oneokrock.com/wp-content/themes/oor_pc/images/common/main_arrow_left_off.gif"}/
        %a.next{:href => "javascript: void(0);"}
          %img.h{:alt => "", :src => "http://www.oneokrock.com/wp-content/themes/oor_pc/images/common/main_arrow_right_off.gif"}/
      .banners
        %ul.w
          %li{:style => "left: -50px; opacity: 1; z-index: 0; display: block;"}
            %a{:href => "http://www.oneokrock.com/jp/tour/"}
              %img{:alt => "", :src => "http://www.oneokrock.com/wp-content/uploads/2019/07/144a49a6cc7000195d915675eaf7e159.jpg"}/
          %li{:style => "left: -50px; opacity: 1; display: block; z-index: 0;"}
            %a{:href => ""}
              %img{:alt => "", :src => "http://www.oneokrock.com/wp-content/uploads/2019/06/8637badb4fd83b5352634d8bbb3e3c29.jpg"}/
          %li{:style => "left: -50px; opacity: 1; display: block; z-index: 0;"}
            %a{:href => "http://www.oneokrock.com/jp/news/"}
              %img{:alt => "", :src => "http://www.oneokrock.com/wp-content/uploads/2018/11/cd05_banner3.jpg"}/
        .shadow_top
          %img{:alt => "", :src => "http://www.oneokrock.com/wp-content/themes/oor_pc/images/common/main_shadow_top.png"}/
        .shadow_bottom
          %img{:alt => "", :src => "http://www.oneokrock.com/wp-content/themes/oor_pc/images/common/main_shadow_bottom.png"}/
      %ul.indicators
        %li
          %i
        %li
          %i
        %li.current
          %i
      -#  main_banner
    
    .two_col
      .main_col
        #topics
          %h2
            %img{:alt => "TOPICS", :src => "http://www.oneokrock.com/wp-content/themes/oor_pc/images/common/h2_topics.png"}/
          %ul.topic_list
            %li
              .image
                %a{:href => "http://www.oneokrock.com/jp/news/2817"}
                  %img{:alt => "topic_1", :src => "http://www.oneokrock.com/wp-content/uploads/2019/07/one-ok-rock_tour_0710v3-e1563508374628.jpg", :width => "180"}/
              .description
                %p.date
                  2019.07.24
                  %i.icon
                %h3.title
                  %a.w_o{:href => "http://www.oneokrock.com/jp/news/2817"} ONE OK ROCK 2019 - 2020 "Eye of the Storm" JAPAN TOUR (代々木・沖縄公演　追加)
                .headline_color-mid
                  【ONE OK ROCK 2019 – 2020 “Eye of the Storm” JAPAN TOUR】
                  %span.color-accent_read_more
                    %a.ul.color-accent{:href => "http://www.oneokrock.com/jp/news/2817"} ［READ MORE］
            %li
              .image
                %a{:href => "http://www.oneokrock.com/jp/news/2801"}
                  %img{:alt => "topic_1", :src => "http://www.oneokrock.com/wp-content/uploads/2019/06/mini_web_190618_oor_ambitions_jacket_fix-e1560850240767.jpg", :width => "180"}/
              .description
                %p.date
                  2019.06.20
                  %i.icon
                %h3.title
                  %a.w_o{:href => "http://www.oneokrock.com/jp/news/2801"} LIVE DVD&amp;Blu-ray "ONE OK ROCK 2018 AMBITIONS JAPAN DOME TOUR"
                .headline_color-mid
                  LIVE DVD&amp;Blu-ray “ONE OK ROCK 2018 AMBITIONS JAPAN DOME TOUR”
                  %span.color-accent_read_more
                    %a.ul.color-accent{:href => "http://www.oneokrock.com/jp/news/2801"} ［READ MORE］
            %li
              .image
                %a{:href => "http://www.oneokrock.com/jp/news/2558"}
                  %img{:alt => "topic_1", :src => "http://www.oneokrock.com/wp-content/uploads/2018/11/Eye-of-the-Storm_ASK_JK_small-e1542102816399.jpg", :width => "180"}/
              .description
                %p.date
                  2018.11.23
                  %i.icon
                %h3.title
                  %a.w_o{:href => "http://www.oneokrock.com/jp/news/2558"} アルバム  「Eye of the Storm」発売決定＆収録曲「Stand Out Fit In」が配信開始
                .headline_color-mid
                  ONE OK ROCK約2年ぶりとなるアルバム「Eye of the Storm」発売決定！
                  %span.color-accent_read_more
                    %a.ul.color-accent{:href => "http://www.oneokrock.com/jp/news/2801"} ［READ MORE］
      -# .main_col
      .sub_col
        #sns
          %ul.sns_list
            %li
              %a.o{:href => "https://twitter.com/ONEOKROCK_japan", :target => "_blank"}
                %i.icon_twitter
                  %img{:src => "http://www.oneokrock.com/wp-content/themes/oor_pc/images/sprite/twitter.png"}/
            %li
              %a.o{:href => "https://www.facebook.com/ONEOKROCK", :target => "_blank"}
                %i.icon_facebook
                  %img{:src => "http://www.oneokrock.com/wp-content/themes/oor_pc/images/sprite/facebook.png"}/
            %li
              %a.o{:href => "http://instagram.com/oneokrockofficial", :target => "_blank"}
                %i.icon_instagram
                  %img{:src => "http://www.oneokrock.com/wp-content/themes/oor_pc/images/sprite/instagram.png"}/
            %li
              %a.o{:href => "https://www.youtube.com/user/ONEOKROCKchannel", :target => "_blank"}
                %i.icon_youtube
                  %img{:src => "http://www.oneokrock.com/wp-content/themes/oor_pc/images/sprite/youtube.png"}/
            %li
              %a.o{:href => "http://smarturl.it/ONEOKROCK", :target => "_blank"}
                %i.icon_itune
                  %img{:src => "http://www.oneokrock.com/wp-content/themes/oor_pc/images/sprite/itune.png"}/
            %li
              %a.o{:href => "https://play.spotify.com/artist/7k73EtZwoPs516ZxE72KsO", :target => "_blank"}
                %i.icon_spotify
                  %img{:src => "http://www.oneokrock.com/wp-content/themes/oor_pc/images/sprite/spotify.png"}/
        -# sns
        #pickup_video
          .youtube
            %iframe{:allowfullscreen => "", :frameborder => "0", :height => "208", :src => "http://www.youtube.com/embed/uyaKoj7wABY/?wmode=transparent", :width => "369"}
          %p.more
            %a.o.inverse{:href => ""}
              %img{:alt => "MORE VIDEOS", :src => "http://www.oneokrock.com/wp-content/themes/oor_pc/images/common/btn_more_videos.png"}/
        -# pickup_video
        #twitter_widget
          %h2
            %img{:alt => "TWITTER", :src => "http://www.oneokrock.com/wp-content/themes/oor_pc/images/common/h2_twitter.png"}/
          %p.follow
            %a.o{:href => "http://twitter.com/ONEOKROCK_japan", :target => "_blank"}
              %img{:alt => "FOLLOW", :src => "http://www.oneokrock.com/wp-content/themes/oor_pc/images/common/btn_follow.png"}/
        -# twitter_widget
        #side_banners
          %ul.banner_list
            %li
              %a.o{:href => "https://oneokrock-pf.com/", :target => "_blank"}
                %img{:alt => "", :src => "http://www.oneokrock.com/wp-content/themes/oor_pc/images/side_banner/side_banner_1.png"}/
            %li
              %a.o{:href => "https://oneokrock-pf.com/", :target => "_blank"}
                %img{:alt => "", :src => "http://www.oneokrock.com/wp-content/themes/oor_pc/images/side_banner/side_banner_2.png"}/
        -# side_banners
    #return_top
      %a.o{:href => "#"}
        %img{:alt => "RETURN PAGE TOP", :src => "http://www.oneokrock.com/wp-content/themes/oor_pc/images/common/btn_return_top.png"}/
  %footer
    .content_base
      %p.copyright
        %img{:alt => "copyright", :height => "8", :src => "http://www.oneokrock.com/wp-content/themes/oor_pc/images/common/copyright.png", :width => "179"}/

app/views/tweets/destroy.html.haml
%header
  .header_base
    %h1
      %img{:alt => "ONE OK ROCK", :src => "http://www.oneokrock.com/wp-content/themes/oor_pc/images/common/logo_top.png"}
  .contents.row
    .success
      %h3
        Deletion completed
      %a.btn{href: tweets_path(@tweets)} Return to Post List

app/views/tweets/edit.html.haml
%header
  .header_base
    %h1
      = link_to image_tag("http://www.oneokrock.com/wp-content/themes/oor_pc/images/common/logo_top.png"), "/"
  .contents.row_a
    .container
      = form_for @tweet do |form|
        %h3
          Edit
        = form.text_field :name, placeholder: "Nickname"
        = form.text_field :image, placeholder: "Image Url"
        = form.text_area :text, placeholder: "text" , rows: "10"
        = form.submit "SEND"

app/views/tweets/index.html.haml
%header
  .header_base
    %h1
      = link_to image_tag("http://www.oneokrock.com/wp-content/themes/oor_pc/images/common/logo_top.png"), "/"
      .content_btn_post
        =link_to new_tweet_path(@tweet) do
          New post
        %img.hf{:src => "http://www.oneokrock.com/wp-content/themes/oor_pc/images/sprite/caret-right.png"}/
  -# = form_for (search_tweets_path), method: :get, class: "search-form" do |form|
  -#   = form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input"
  -#   = form.submit "検索", class: "search-btn"
  .contents.row
    - @tweets.each do |tweet|
      .content_post{style: "background-image: url(#{tweet.image});"}
        .more
          %span= image_tag 'arrow_top.png'
          %ul.more_list
            %li
              = link_to 'Show', "/tweets/#{tweet.id}", method: :get
            - if user_signed_in? && current_user.id == tweet.user_id 
              %li
                = link_to 'Edit', "/tweets/#{tweet.id}/edit", method: :get
              %li
                = link_to 'Destroy', "/tweets/#{tweet.id}", method: :delete
        = simple_format(tweet.text)
        %span.name
          %a{href: "/users/#{tweet.user.id}"}
            Contributor
            = tweet.user.name
    = paginate(@tweets)

app/views/tweets/new.html.haml
%header
  .header_base
    %h1
      = link_to image_tag("http://www.oneokrock.com/wp-content/themes/oor_pc/images/common/logo_top.png"), "/"
  .contents.row_a
    .container
      = form_for @tweet do |form|
        %h3
          Post
        = form.text_field :image, placeholder: "Image Url"
        = form.text_area :text, placeholder: "text" , rows: "10"
        = form.submit "SEND"

app/views/tweets/show.html.haml
%header
  .header_base
    %h1
      = link_to image_tag("http://www.oneokrock.com/wp-content/themes/oor_pc/images/common/logo_top.png"), tweets_path(current_user)
  .contents.row
    .content_post{:style => "background-image: url(#{@tweet.image});"}
      - if user_signed_in? && current_user.id == @tweet.user_id
        .more
          %span= image_tag 'arrow_top.png'
          %ul.more_list
            %li
              = link_to 'Edit', "/tweets/#{@tweet.id}/edit", method: :get
            %li
              = link_to 'Destroy', "/tweets/#{@tweet.id}", method: :delete
        = simple_format(@tweet.text)
        %span.name
          Contributor
          = @tweet.user.name
    .container
      - if current_user
        = form_for [@tweet, @comment] do |form|
          = form.text_area :text, placeholder: "Comment", rows: "2",class: "textbox"
          = form.submit "SEND",class: "form__submit"
      - else
        %strong
          %p ※※※ コメントの投稿には新規登録/ログインが必要です ※※※
      .comments
        %h4 ＜Comment list＞
        - if @comments
          - @comments.each do |comment|
            %p
              %strong
                = link_to comment.user.name, "/users/#{comment.user_id}"
                = comment.text
  %footer
    .content_base
      %p.copyright
        %img{:alt => "copyright", :height => "8", :src => "http://www.oneokrock.com/wp-content/themes/oor_pc/images/common/copyright.png", :width => "179"}/